import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiFetch, getCurrentUser, logout, readJson } from "../api";

const initialRequirements = { requiredGender: "", minAge: "", maxAge: "", minHeight: "", maxHeight: "", requiredCategories: "", requiredSkills: "" };
const splitList = (value) => value.split(",").map((item) => item.trim()).filter(Boolean);

export default function ClientDashboard() {
  const navigate = useNavigate();
  const [user, setUser] = useState(null); const [events, setEvents] = useState([]); const [requests, setRequests] = useState([]);
  const [title, setTitle] = useState(""); const [startDate, setStartDate] = useState(""); const [requirements, setRequirements] = useState(initialRequirements); const [error, setError] = useState("");
  const load = async () => { try { const [{ user: current }, mine] = await Promise.all([getCurrentUser(), readJson(await apiFetch("/events/mine"))]); if (current.role !== "client") throw new Error("This account cannot access the client portal."); setUser(current); setEvents(mine.events || []); setRequests(mine.requests || []); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, []);
  const create = async (event) => { event.preventDefault(); setError(""); try { await readJson(await apiFetch("/events", { method: "POST", body: JSON.stringify({ title, eventType: "Event", startDate, location: "To be confirmed", description: title, requiredGender: requirements.requiredGender || undefined, minAge: requirements.minAge === "" ? undefined : Number(requirements.minAge), maxAge: requirements.maxAge === "" ? undefined : Number(requirements.maxAge), minHeight: requirements.minHeight === "" ? undefined : Number(requirements.minHeight), maxHeight: requirements.maxHeight === "" ? undefined : Number(requirements.maxHeight), requiredCategories: splitList(requirements.requiredCategories), requiredSkills: splitList(requirements.requiredSkills) }) })); setTitle(""); setStartDate(""); setRequirements(initialRequirements); await load(); } catch (err) { setError(err.message); } };
  const review = async (id, status) => { try { await readJson(await apiFetch(`/events/requests/${id}`, { method: "PATCH", body: JSON.stringify({ status }) })); await load(); } catch (err) { setError(err.message); } };
  const remove = async (id) => { try { await readJson(await apiFetch(`/events/${id}`, { method: "DELETE" })); await load(); } catch (err) { setError(err.message); } };
  const updateRequirement = (key, value) => setRequirements({ ...requirements, [key]: value });
  if (!user) return <main style={styles.page}><p>{error || "Loading account..."}</p></main>;
  return <main style={styles.page}><section style={styles.container}>
    <header style={styles.header}><div><p style={styles.eyebrow}>MODELNEXT CLIENT PORTAL</p><h1 style={styles.title}>Welcome, {user.name}</h1><p style={styles.muted}>Create an event and use AI recommendations to find approved talent.</p></div><button type="button" style={styles.secondaryButton} onClick={async () => { await logout(); navigate("/login"); }}>Log out</button></header>
    {error && <p style={styles.error} role="alert">{error}</p>}
    <section style={styles.card}><h2 style={styles.sectionTitle}>Create event</h2><form onSubmit={create} style={styles.form}>
      <input required style={styles.input} placeholder="Event name" value={title} onChange={(event) => setTitle(event.target.value)} />
      <input required style={styles.input} type="datetime-local" value={startDate} onChange={(event) => setStartDate(event.target.value)} />
      <h3 style={styles.requirementTitle}>AI matching requirements <span style={styles.optional}>(all optional)</span></h3><div style={styles.grid}>
        <select style={styles.input} value={requirements.requiredGender} onChange={(event) => updateRequirement("requiredGender", event.target.value)}><option value="">Any gender</option><option value="Female">Female</option><option value="Male">Male</option><option value="Other">Other</option></select>
        <input style={styles.input} type="number" min="0" placeholder="Minimum age" value={requirements.minAge} onChange={(event) => updateRequirement("minAge", event.target.value)} />
        <input style={styles.input} type="number" min="0" placeholder="Maximum age" value={requirements.maxAge} onChange={(event) => updateRequirement("maxAge", event.target.value)} />
        <input style={styles.input} type="number" min="0" placeholder="Minimum height (cm)" value={requirements.minHeight} onChange={(event) => updateRequirement("minHeight", event.target.value)} />
        <input style={styles.input} type="number" min="0" placeholder="Maximum height (cm)" value={requirements.maxHeight} onChange={(event) => updateRequirement("maxHeight", event.target.value)} />
        <input style={styles.input} placeholder="Categories, comma separated" value={requirements.requiredCategories} onChange={(event) => updateRequirement("requiredCategories", event.target.value)} />
        <input style={styles.input} placeholder="Skills, comma separated" value={requirements.requiredSkills} onChange={(event) => updateRequirement("requiredSkills", event.target.value)} />
      </div><button style={styles.primaryButton}>Create event</button></form></section>
    <section style={styles.card}><h2 style={styles.sectionTitle}>Participation requests</h2>{requests.length === 0 ? <p style={styles.muted}>No pending participation requests.</p> : requests.map((request) => <div key={request.id} style={styles.row}><span>{request.requesterRole} requested to join <strong>{request.eventTitle}</strong></span><span><button type="button" style={styles.smallPrimary} onClick={() => review(request.id, "confirmed")}>Approve</button><button type="button" style={styles.smallSecondary} onClick={() => review(request.id, "declined")}>Decline</button></span></div>)}</section>
    <section style={styles.card}><h2 style={styles.sectionTitle}>My events</h2>{events.length === 0 ? <p style={styles.muted}>Create an event to start receiving AI recommendations.</p> : events.map((event) => <article key={event.id} style={styles.event}><div><h3 style={styles.eventTitle}>{event.title}</h3><p style={styles.muted}>{event.status} · {new Date(event.startDate).toLocaleString()}</p></div><div><button type="button" style={styles.smallPrimary} onClick={() => navigate(`/client-portal/ai-matches/${event.id}`)}>Find AI matches</button><button type="button" style={styles.smallSecondary} onClick={() => remove(event.id)}>Delete</button></div></article>)}</section>
  </section></main>;
}

const styles = {
  page: { minHeight: "100vh", background: "#0c0c0c", color: "#f5f5f5", padding: "52px 24px", boxSizing: "border-box" }, container: { maxWidth: 1050, margin: "0 auto" }, header: { display: "flex", justifyContent: "space-between", gap: 24, alignItems: "start", marginBottom: 30 }, eyebrow: { margin: 0, color: "#9bbdcd", fontSize: 11, letterSpacing: 2, fontWeight: 700 }, title: { margin: "8px 0", fontSize: 36 }, muted: { color: "#a5a5a5", margin: "6px 0" }, card: { background: "#171717", border: "1px solid #343434", borderRadius: 14, padding: 24, marginBottom: 20 }, sectionTitle: { margin: "0 0 18px", fontSize: 21 }, requirementTitle: { gridColumn: "1 / -1", margin: "4px 0 0", fontSize: 14, color: "#d9edf7" }, optional: { color: "#a5a5a5", fontWeight: 400 }, form: { display: "grid", gap: 12 }, grid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 12 }, input: { background: "#252525", color: "#f5f5f5", border: "1px solid #464646", borderRadius: 8, padding: "12px 13px", boxSizing: "border-box", width: "100%" }, primaryButton: { justifySelf: "start", background: "#d9edf7", color: "#111", border: 0, borderRadius: 8, padding: "12px 18px", fontWeight: 700, cursor: "pointer" }, secondaryButton: { background: "transparent", color: "#f5f5f5", border: "1px solid #565656", borderRadius: 8, padding: "10px 14px", cursor: "pointer" }, smallPrimary: { background: "#d9edf7", color: "#111", border: 0, borderRadius: 7, padding: "8px 10px", fontWeight: 700, cursor: "pointer", marginLeft: 8 }, smallSecondary: { background: "transparent", color: "#eee", border: "1px solid #565656", borderRadius: 7, padding: "7px 9px", cursor: "pointer", marginLeft: 8 }, row: { display: "flex", justifyContent: "space-between", gap: 16, alignItems: "center", padding: "13px 0", borderTop: "1px solid #303030" }, event: { display: "flex", justifyContent: "space-between", gap: 16, alignItems: "center", padding: "15px 0", borderTop: "1px solid #303030" }, eventTitle: { margin: 0, fontSize: 17 }, error: { color: "#ff9c9c", margin: "0 0 18px" },
};
